baseURL = "https://mokelentertainment.com/"
title = "Mokel Entertainment"
author = "nsaccente"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = false

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = [
    'blog',
    'drone',
    'film',
    'music',
    'video',
  ]

  googleFonts = true

  [params.logo]
    main = "img/logo/me_logo.png"
    alt = "Mokel Entertainment Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Mokel Entertainment"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "The official site for content from Mokel Entertainment studios."
    meta_og_title = "Mokel Entertainment"
    meta_og_type = "website"
    meta_og_url = "https://mokelentertainment.com/"
    meta_og_image = ""
    meta_og_description = "The official site for content from Mokel Entertainment studios."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    identifier = "dron"
    name = "Drone"
    url = "/drone/"
    weight = 20

  [[menu.main]]
    identifier = "film"
    name = "Film"
    url = "/film/"
    weight = 30

  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 40

  [[menu.main]]
    identifier = "video"
    name = "Video"
    url = "/video/"
    weight = 50

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 60

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 70

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Facebook"
    url = "https://www.facebook.com/Mokel2419"
    pre = "<i class='icon-facebook text-2xl'></i>"
    weight = 10

[[menu.footer]]
    name = "Discord"
    url = "https://www.discord.com/"
    pre = "<i class='icon-discord text-2xl'></i>"
      weight = 20

[[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/MokelEnter_ME"
    pre = "<i class='icon-twitter text-2xl'></i>"
      weight = 30
