backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/img/content`" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" , default: "Michael Strick" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", default: "img/content/blog/default.jpg", optional: true}
      - { label: "Weight", name: "weight", widget: "number" , default: 100 }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: "To embed a Youtube video, copy and paste: {{< youtube abc123 >}}' where abc123 is the video id. " }

  - name: "drone" 
    label: "Drone" 
    folder: "content/drone" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" , default: "Michael Strick" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", default: "img/content/drone/default.jpg", optional: true}
      - { label: "Weight", name: "weight", widget: "number" , default: 100 }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: "To embed a Youtube video, copy and paste: {{< youtube abc123 >}}' where abc123 is the video id. " }

  - name: "film" 
    label: "Film" 
    folder: "content/film"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" , default: "Michael Strick" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", default: "img/content/film/default.jpg", optional: true}
      - { label: "Weight", name: "weight", widget: "number" , default: 100 }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: "To embed a Youtube video, copy and paste: {{< youtube abc123 >}}' where abc123 is the video id. " }

  - name: "music" 
    label: "Music" 
    folder: "content/music"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" , default: "Michael Strick" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", default: "img/content/music/default.jpg", optional: true}
      - { label: "Weight", name: "weight", widget: "number" , default: 100 }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: "To embed a Youtube video, copy and paste: {{< youtube abc123 >}}' where abc123 is the video id. " }
    
  - name: "video" 
    label: "Video" 
    folder: "content/video"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" , default: "Michael Strick" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", default: "img/content/video/default.jpg", optional: true}
      - { label: "Weight", name: "weight", widget: "number" , default: 100 }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: "To embed a Youtube video, copy and paste: {{< youtube abc123 >}}' where abc123 is the video id. " }
    
    
